google_voice_parser_grid:
    pattern:  /grid
    defaults: { _controller: GoogleVoiceParserFirstBundle:Default:index }
google_voice_parser_chart:
    pattern:  /chart
    defaults: { _controller: GoogleVoiceParserFirstBundle:Plot:index }
