parameters:
    # @todo, a better name than data getter.
    google_voice_parser.data_getter.class: GoogleVoiceParser\FirstBundle\DataGetter
    # @todo come up with a default location that is relative. To the app root?
    google_voice_parser.data_getter.directory: "/Users/stevepersch/Sites/google_voice_parser/source_files"

services:
    google_voice_parser_first.data_getter:
        class: %google_voice_parser.data_getter.class%
        arguments: [%google_voice_parser.data_getter.directory%]
